np-guard/vpc-network-config-analyzer

cmd/analyzer/main.go, pkg/ibmvpc/analysis_output_test.go, pkg/ibmvpc/examples/experiments_env_all_vpcs.json, pkg/ibmvpc/examples/experiments_env_all_vpcs.txt, pkg/ibmvpc/examples/experiments_env_test-vpc1-ky.json, pkg/ibmvpc/examples/experiments_env_test-vpc2-ky.json, pkg/ibmvpc/examples/multiple_vpcs_all_vpcssubnetsBased_withPGW.txt, pkg/ibmvpc/parser.go, pkg/vpcmodel/debugOutput.go, pkg/vpcmodel/drawioOutput.go, pkg/vpcmodel/jsonOutput.go, pkg/vpcmodel/mdOutput.go, pkg/vpcmodel/output.go, pkg/vpcmodel/textOutput.go, pkg/vpcmodel/vpcConfig.go
issue #53 follow-ups:
(1) keep in VPCConfig an abstract member of type VPCResourceIntf which points to the concrete VPC the config belongs to, and delete vpcsMap
(2) support multiple vpcs with format JSON
=> Issue 53 additional updates

pkg/ibmvpc/analysis_output_test.go, pkg/ibmvpc/examples/input_sg_testing_3.json, pkg/ibmvpc/examples/sg_testing_3.txt, pkg/ibmvpc/examples/sg_testing_3subnetsBased_withPGW.txt, pkg/ibmvpc/nacl_analysis.go, pkg/ibmvpc/parser.go, pkg/ibmvpc/vpc.go, pkg/vpcmodel/externalNetwork.go
=> Fix issue sg testing 3

pkg/ibmvpc/examples/acl_testing3endpointsDiff.txt, pkg/ibmvpc/examples/acl_testing5subnetsDiff.txt, pkg/vpcmodel/grouping.go, pkg/vpcmodel/grouping_test.go, pkg/vpcmodel/mdOutput.go, pkg/vpcmodel/nodesConnectivity.go, pkg/vpcmodel/semanticDiff.go, pkg/vpcmodel/semanticDiff_test.go, pkg/vpcmodel/subnetsConnectivity.go, pkg/vpcmodel/vpcConnectivity.go
=> 209 grouping semantic diff new

cmd/analyzer/main.go, pkg/ibmvpc/sg_analysis.go, pkg/vpcmodel/nodesExplainability..go
first step in solution for 
https://github.com/np-guard/vpc-network-config-analyzer/issues/42
Specifically, simple required functionality added in both ends of the solution.
=> 42 explanability 1

README.md, cmd/analyzer/parse_args.go
command line help should tell which output format is supported for which analysis
=> improve cli command-line help

pkg/ibmvpc/explainability_test.go, pkg/vpcmodel/nodesExplainability.go, pkg/vpcmodel/output.go
=> 318 improve unitests

pkg/ibmvpc/parser.go, pkg/vpcmodel/grouping_test.go, pkg/vpcmodel/utils.go
=> issue #324: small fixes

pkg/ibmvpc/connectivityAnalysis_test.go, pkg/ibmvpc/ibmDrawioGenerator.go, pkg/ibmvpc/nacl_analysis.go, pkg/ibmvpc/parser.go, pkg/ibmvpc/vpc.go, pkg/vpcmodel/abstractVPC.go, pkg/vpcmodel/drawioOutput.go, pkg/vpcmodel/explainabilityInput.go, pkg/vpcmodel/grouping.go, pkg/vpcmodel/groupingSelfLoop.go, pkg/vpcmodel/grouping_test.go, pkg/vpcmodel/semanticDiff.go, pkg/vpcmodel/semanticDiff_test.go, pkg/vpcmodel/subnetsConnectivity.go, pkg/vpcmodel/vpcConfig.go
=> 380 abstract vpc and subnet

pkg/drawio/styles.go
styling the lines according to:
https://github.com/np-guard/vpc-network-config-analyzer/issues/415
=> Line formating

pkg/ibmvpc/parser.go, pkg/ibmvpc/vpc.go
Few updates as preparation for #496 : 
- parser updates: separate functions that return the created resources, so that can be reused in unit-tests. 
- vpc struct update: add field `addressPrefixesIPBlock`
=> Parser updates

pkg/ibmvpc/implicit_routing.go, pkg/ibmvpc/routing_tables_analysis.go, pkg/ibmvpc/routing_tables_test.go
=> routing tables analysis wip

pkg/ibmvpc/examples/out/explain_out/SGInternal3SrcToExternalGroup_all_vpcs_explain_debug.txt, pkg/ibmvpc/examples/out/explain_out/SimpleExternalSG4_all_vpcs_explain.txt, pkg/ibmvpc/examples/out/explain_out/multiVPCVsiToExternalMissingRouter_all_vpcs_explain_debug.txt, pkg/ibmvpc/explainability_test.go, pkg/vpcmodel/explainabilityInput.go, pkg/vpcmodel/explainabilityPrint.go
fixes #541 please see my comments in the issue
=> 541 explain cosmetic

pkg/ibmvpc/analysis_output_test.go, pkg/ibmvpc/examples/input/input_nacl_split_subnet.json, pkg/ibmvpc/examples/out/analysis_out/nacl_split_subnet_all_vpcs_.txt, pkg/vpcmodel/subnetsConnectivity.go
=> fix issue with NACL splitting subnet connectivity 

cmd/analyzer/main.go, cmd/analyzer/main_test.go, cmd/analyzer/subcmds/analysis.go, cmd/analyzer/subcmds/diff.go, cmd/analyzer/subcmds/explain.go, cmd/analyzer/subcmds/report.go, pkg/ibmvpc/examples/input/input_split_subnet.json, pkg/logging/logger.go
=> Avoid printing usage message on semantic errors

pkg/ibmvpc/analysis_output_test.go, pkg/ibmvpc/examples/.gitignore
please notice that gitignore is also updated
this might cause html files to appear.
these file should be manually be deleted
=> do not create html & svg 

go.mod, go.sum, pkg/ibmvpc/parser.go, pkg/ibmvpc/routing_tables_analysis.go, pkg/ibmvpc/sg_analysis.go, pkg/ibmvpc/vpc.go, pkg/vpcmodel/explainabilityInput.go, pkg/vpcmodel/subnetsConnectivity.go
=> Using IPBlock.Overlap()

pkg/drawio/layoutOverlap.go, pkg/ibmvpc/analysis_output_test.go
fixing https://github.com/np-guard/vpc-network-config-analyzer/issues/651
=> too many bypass points in layout

README.md, cmd/analyzer/main_test.go, cmd/analyzer/subcmds/diff.go, cmd/analyzer/subcmds/root.go, cmd/analyzer/subcmds/vpcconfigs.go, vpcanalyzer_diff.md, vpcanalyzer_explain.md, vpcanalyzer_report.md
Changed flags:
```
-c, --config
-f, --filename
-o, --output
```
=> update cli flags + readme

pkg/awsvpc/analysis_output_test.go, pkg/commonvpc/parser.go, pkg/vpcmodel/rulesDetailsProvider.go
just a quick fix to allow html output for aws:
=> Initial html aws

pkg/vpcmodel/drawioOutput.go
bug fix - routers are ignored in non-grouping mode
=> bug fix - routers are ignored in non-grouping mode

pkg/ibmvpc/parser.go, pkg/ibmvpc/vpc.go, pkg/vpcmodel/abstractVPC.go
preparation to internet gateway
=> adding SetExternalDestinations() to router interface

cmd/analyzer/subcmds/analysis.go, pkg/awsvpc/analysis_output_test.go, pkg/awsvpc/parser.go, pkg/ibmvpc/analysis_output_test.go, pkg/ibmvpc/ingress_routing_test.go, pkg/ibmvpc/parser.go, pkg/ibmvpc/parser_test.go, pkg/vpcmodel/drawioOutput.go, pkg/vpcmodel/multi_vpc_config.go, pkg/vpcmodel/output.go
fixed the bug.
on the way, the code got much more simpler
=> Set default provider for drawio

pkg/ibmvpc/analysis_output_test.go, pkg/ibmvpc/vpc.go, pkg/vpcmodel/abstractVPC.go, pkg/vpcmodel/drawioOutput.go
add the subnets as potential sources.
=> Drawio gpw on subnet mode

pkg/awsvpc/examples/out/explain_out/ip_to_ip_all_vpcs_explain_detail.txt, pkg/awsvpc/explainability_test.go, pkg/commonvpc/analysis_output_test_functionality.go, pkg/ibmvpc/explainability_test.go
creating new file 
moved some code to common vpc
=> Exp aws example platform

cmd/analyzer/subcmds/vpcconfigs.go, pkg/awsvpc/parser.go, pkg/ibmvpc/parser.go
=> Allow setting the --provider flag to aws

pkg/awsvpc/examples/out/explain_out/ip_to_ip_all_vpcs_explain_detail.txt, pkg/awsvpc/parser.go, pkg/awsvpc/sg_analysis.go
user can give a valid sg name.
this name is kept at the resource tag, not in the "GroupName" entry
=> Get sg name

go.mod, go.sum, pkg/ibmvpc/examples/input/input_subnet_grouping.json, pkg/ibmvpc/examples/out/synthesis_out/acl_testing5_all_vpcs_subnetsBased_withPGW_with_grouping.json, pkg/ibmvpc/examples/out/synthesis_out/subnet_grouping_all_vpcs_subnetsBased_withPGW_with_grouping.json, pkg/ibmvpc/synthesis_output_test.go, pkg/vpcmodel/grouping.go, pkg/vpcmodel/output.go, pkg/vpcmodel/synthesisOutput.go
=> support segments synthesis

pkg/ibmvpc/examples/input/input_multi_regions.json, pkg/ibmvpc/examples/input/input_multi_resource_groups.json, pkg/ibmvpc/examples/input/input_tgw_basic_example.json, pkg/ibmvpc/examples/input/input_tgw_basic_example_multiple_regions.json, pkg/ibmvpc/examples/input/input_tgw_basic_example_with_some_default_deny.json, pkg/ibmvpc/examples/input/input_tgw_larger_example.json, pkg/ibmvpc/examples/input/input_tgw_larger_example_dup_names.json, pkg/ibmvpc/examples/input/input_tgw_larger_example_partly_overlap.json, pkg/ibmvpc/tgw_analysis.go
fix current tests with overlapping address prefixes + Remove function validateAddressPrefixesExist()
=> fix current tests with overlapping address prefixes + Remove function

go.mod, pkg/common/genericSet.go, pkg/drawio/layout.go, pkg/linter/linterExecute.go
=> Use the new map/slice features in Go 1.23

pkg/commonvpc/nacl_analysis.go, pkg/ibmvpc/connectivityAnalysis_test.go, pkg/ibmvpc/naclAnalysis_test.go
this is continue to https://github.com/np-guard/vpc-network-config-analyzer/pull/932 branch
=> 318 improve unittests
